name: minio_flutter
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.10.0
  http: ^1.1.2
  crypto: ^3.0.3
  convert: ^3.1.1
  xml: ^6.5.0
  buffer: ^1.2.2
  intl: ^0.19.0
  mime: ^1.0.4
  path: ^1.8.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pedantic: ^1.11.1
  html: ^0.15.4

flutter:
